### ISSUE TITLE
Global node and npm dependencies should be stated

### ISSUE THREAD

**Issue by blokhin** [Exabyte-io/materials-designer#24]
I have npm 5.5.1 and node 8.9.3 on Cygwin, `npm start` produces:
```
PORT=3001 react-scripts start
'PORT' is not recognized as an internal or external command
```

After I run directly `PORT=3001 ./node_modules/.bin/react-scripts start` it says:
```
Compiling...
Failed to compile.
```
The web-browser starts, however the console says: `Uncaught Error: Cannot find module 'C:\<...>\materials-designer\node_modules\babel-preset-react-app\node_modules\@babel\runtime/helpers/createForOfIteratorHelper'`

**Comment by blokhin** [comment]
Alright, the same thing (Failed to compile) on 10th Debian, npm 5.8.0 and node 10.15.2.

**Comment by timurbazhirov** [comment]
We've faced this before and resolved by using npm at 6.4.1. and Node 8.11.4 [in this PR](https://stackoverflow.com/questions/32964900/how-do-you-run-a-js-file-using-npm-scripts) for [Wave.js](https://github.com/Exabyte-io/wave.js). Does it help?

**Comment by blokhin** [comment]
No problem, I'll give it another try after installing the proper version of Node and npm.

**Comment by timurbazhirov** [comment]
Using https://github.com/nvm-sh/nvm might be helpful

**Comment by blokhin** [comment]
```
# npm -v
6.4.1
# node -v
v8.11.4
# git clone https://github.com/Exabyte-io/materials-designer
# cd materials-designer/
# npm install --no-save
# cd node_modules/@babel/runtime
# ln -sf ../runtime-corejs2/core-js .
# cd -
# npm start

Failed to compile.

./node_modules/chalk/index.js
Module not found: Can't resolve '/root/materials-designer/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/createForOfIteratorHelper' in '/root/materials-designer/node_modules/chalk'
```

**Comment by blokhin** [comment]
```
du -sh materials-designer/
455M    materials-designer/
```
I kind of like the modern JavaScript :dancers:

**Comment by timurbazhirov** [comment]
Might be a problem with package versions. Can you post the output of `npm list`, please?

**Comment by blokhin** [comment]
Please, see here: https://pastebin.com/05pwKC7y

**Comment by blokhin** [comment]
These strings may signal about the source of the error:
```
â”‚ â”‚ â”œâ”€â”€ UNMET OPTIONAL DEPENDENCY fsevents@^1.2.7
â”‚ â”œâ”€â”€ UNMET PEER DEPENDENCY material-ui@^1.0.0-beta.16
â”œâ”€â”€ UNMET PEER DEPENDENCY material-ui@^1.0.0-beta.16
â”‚ â”œâ”€â”¬ UNMET PEER DEPENDENCY @babel/core@7.2.2
â”‚ â”‚   â”‚   â”œâ”€â”€ UNMET OPTIONAL DEPENDENCY fsevents@^1.2.3

npm ERR! peer dep missing: material-ui@^1.0.0-beta.16, required by material-ui-icons-next@1.0.0-beta.17-next
npm ERR! extraneous: fsevents /root/materials-designer/node_modules/fsevents
npm ERR! error in /root/materials-designer/node_modules/fsevents: ENOENT: no such file or directory, open '/root/materials-designer/node_modules/fsevents/package.json'
npm ERR! extraneous: bindings@1.5.0 /root/materials-designer/node_modules/bindings
npm ERR! peer dep missing: material-ui@^1.0.0-beta.16, required by material-ui-icons-next@1.0.0-beta.17-next
npm ERR! peer dep missing: @babel/core@^7.1.0, required by babel-plugin-named-asset-import@0.3.6
npm ERR! error in /root/materials-designer/node_modules/react-scripts/node_modules/fsevents: ENOENT: no such file or directory, open '/root/materials-designer/node_modules/react-scripts/node_modules/fsevents/package.json'
npm ERR! invalid: fsevents /root/materials-designer/node_modules/react-scripts/node_modules/fsevents
npm ERR! extraneous: rc /root/materials-designer/node_modules/react-scripts/node_modules/fsevents/node_modules/rc
npm ERR! error in /root/materials-designer/node_modules/react-scripts/node_modules/fsevents/node_modules/rc: ENOENT: no such file or directory, open '/root/materials-designer/node_modules/react-scripts/node_modules/fsevents/node_modules/rc/package.json'
```
Do you have any idea?

**Comment by timurbazhirov** [comment]
(1) This is related to babel runtime versions and the use of [create-react-app](https://github.com/facebook/create-react-app/issues/7183) package, see https://github.com/Exabyte-io/materials-designer/pull/25/files, use that branch from now on, please, and confirm the resolution.

(2) https://github.com/Exabyte-io/wave.js is more lightweight and might still work as is now

**Comment by blokhin** [comment]
Yes, it starts to work now!

**Comment by blokhin** [comment]
Quick question: can I import my own local / online CIF files? The **import** menu command under **input/output** is inactive.

**Comment by timurbazhirov** [comment]
This is a feature request. In the Exabyte platform, we:

(1) first, upload CIF (or POSCAR) to the database converting it to the [ESSE](https://github.com/Exabyte-io/esse) format on the backend via a (micro)service using a python library ([ExPrESS](https://github.com/Exabyte-io/express)) that can parse and extract the structure from the text ([here](https://github.com/Exabyte-io/express/blob/e9b9191575f636de1836ef9d62275542ec7fe4e8/express/parsers/structure.py)) and then
(2) feed this (JSON) data to the Designer Interface to work with it. 

Having the parsing capability in Made.js directly, would simplify this and remove the need for communication with the backend.

With that said, during the execution of simulations we need to extract data similarly from text files, and having this functionality in python is still convenient too.

Hope this helps.

**Comment by blokhin** [comment]
From the description:

>can be deployed in standalone mode.

Let’s admit, deploying it in the standalone mode just to display silicon is wasting the user‘s time. For example, as of now, I even cannot add it here: https://github.com/blokhin/cif-js-engines

Sorry for off-top.

**Comment by blokhin** [comment]
Also, is there any chance that the slightly wider range of the node / npm versions will be supported, not only npm 6.4.1 and node 8.11.4?
